import { createContext } from 'react'
import type { Locale, MoneyLocale } from './types.ts'
import type { Translator } from './i18n.tsx'

export interface I18nValue { locale: Locale; setLocale: (locale: Locale) => void; t: Translator; moneyLocale: MoneyLocale; numberFormat: MoneyLocale; setNumberFormat: (locale: MoneyLocale) => void }
const fallbackMessages: Record<string, string> = {
  homeLabel: 'Nimvo, home', createFile: 'Create file', openFile: 'Open file', vault: 'Vault', history: 'History', mainNavigation: 'Main navigation', preferences: 'Preferences', footerVersion: 'Nimvo · V2', footerLocal: 'Local data, under your control',
  password: 'Password', passwordConfirmation: 'Confirm password', createVault: 'Create vault', backHome: 'Back to home', minimumPassword: 'At least 8 characters.', newFile: 'New file', createLocalFile: 'Create a local file', createFileDescription: 'Set a password to protect your file. The password is not stored and cannot be recovered.',
  expensesEyebrow: 'Spending', monthlyExpenses: 'Monthly expenses', newExpense: 'New expense', newCategory: 'New category', categoryName: 'Category name', createAndUse: 'Create and use', saveExpense: 'Save expense', amountArs: 'Amount (ARS)', description: 'Description', optional: 'optional', category: 'Category', categorySummary: 'Summary by category', noExpensesSummary: 'No expenses to summarize.', edit: 'Edit', delete: 'Delete', archive: 'Archive', active: 'Active', categories: 'Categories', closeCategories: 'Close categories', createCategory: 'Create category', rename: 'Rename', templateActions: 'Actions',
  newMonthTitle: 'New month', year: 'Year', month: 'Month', income: 'Income', amount: 'Amount', dueDate: 'Due date', monthCreate: 'Create month', amountFor: 'Amount for {concept}', dueFor: 'Due date for {concept}', repeatPreviousIncome: 'Repeat income from previous month ({amount})', enterManualIncome: 'Enter another amount manually', activeTemplates: 'Active templates', noActiveTemplates: 'There are no active templates.', moneyHelp: 'You can use 125000.00 or 125,000.00. Up to two decimals are stored.', invalidMonth: 'Enter a valid year, month, and income.', duplicateMonth: 'That month already exists.', templateAmountInvalid: 'Selected templates need an amount between 0.01 and 999,999,999.00.', dateInvalid: 'Check the due dates.', monthCreateError: 'The month could not be created',
  downloadCopy: 'Download copy', chooseSaveLocation: 'Choose where to save', save: 'Save', actions: 'Actions', saveAs: 'Save as…', linkedFile: 'Linked file: {name}', historyLoadError: 'The history could not be loaded.',
  historyEyebrow: 'Vault / history', monthlyHistory: 'Monthly history', historyLead: 'A comparison of every month, from newest to oldest.', backToMonth: 'Back to month', loadingHistory: 'Loading history…', noMonths: 'There are no months yet', historyEmpty: 'Create a month in the sheet to start building your history.', goToSheet: 'Go to sheet', monthlyHistoryLabel: 'Monthly history', comparisonCaption: 'Amount comparison by month', totalFixed: 'Total fixed expenses', pendingFixedShort: 'Pending fixed expenses', dailyExpenses: 'Daily expenses', breakdown: 'Breakdown', show: 'Show', hide: 'Hide', breakdownOf: 'breakdown for {month}', categoryBreakdownTitle: 'Category breakdown · {month}', noCategoryExpenses: 'No expenses by category', categoriesCountOne: 'category', categoriesCountMany: 'categories', archived: 'Archived',
  openToContinue: 'Open a file to continue.', deleteExpenseTitle: 'Delete this expense?', undoWarning: 'This action cannot be undone.', date: 'Date', chooseCategory: 'Choose a category', noExpenses: 'There are no expenses for this month yet.', settings: 'Settings', close: 'Close', noFixedExpenses: 'There are no fixed expenses for this month yet.', fixedExpensesEyebrow: 'Commitments', fixedExpenses: 'Fixed expenses', newFixedExpense: 'New fixed expense', dueWithoutDate: 'No date', status: 'Status', pending: 'Pending', paid: 'Paid', markPaid: 'Mark as paid', markPending: 'Mark as pending', cancel: 'Cancel', readyTitle: 'Your file is ready.', monthlySheet: 'Monthly sheet', vaultLoadError: 'The vault could not be loaded.', unsavedChanges: 'Unsaved changes', saved: 'Saved', downloadMode: 'Download mode: your browser does not offer direct file access.', previous: 'Previous', next: 'Next', selectMonth: 'Select a month', newMonth: 'New month', monthSummary: 'Monthly summary', pendingFixed: 'Pending fixed expenses', balance: 'Balance', incomeInvalid: 'Income is not valid.', incomeUpdateError: 'Income could not be updated.', templates: 'Templates', lock: 'Lock',
}
const fallbackExtras: Record<string, string> = { currency: 'Currency', amountCurrency: 'Amount ({currency})', currencyUpdateError: 'The currency could not be changed.' }
export const I18nContext = createContext<I18nValue>({ locale: 'en', setLocale: () => undefined, t: (key, values) => { const text = fallbackMessages[key] ?? fallbackExtras[key] ?? key; return values ? text.replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`)) : text }, moneyLocale: 'en-US', numberFormat: 'en-US', setNumberFormat: () => undefined })
