import { expect, test } from '@playwright/test'

test('gestiona gastos, categorías archivadas y resumen del mes', async ({ page }) => {
  await page.goto('/crear')
  await page.getByLabel('Contraseña', { exact: true }).fill('phase4-password')
  await page.getByLabel('Confirmar contraseña').fill('phase4-password')
  await page.getByRole('button', { name: 'Crear bóveda' }).click()
  await expect(page.getByRole('heading', { name: 'Tu archivo está listo.' })).toBeVisible()

  await page.getByRole('button', { name: 'Nuevo mes' }).click()
  await page.getByLabel('Ingresos (ARS)').fill('3500000')
  await page.getByRole('button', { name: 'Crear mes' }).click()
  await expect(page.getByText('Gasto fijo pendiente')).toBeVisible()
  await expect(page.getByRole('region', { name: 'Resumen del mes' })).toContainText('3.500.000,00')

  await page.getByRole('button', { name: 'Nuevo gasto fijo' }).click()
  await page.getByLabel('Concepto').fill('Gasto fijo pagado')
  await page.getByLabel('Importe (ARS)').fill('2000000')
  await page.getByRole('button', { name: 'Guardar gasto fijo' }).click()
  await page.getByRole('button', { name: 'Nuevo gasto fijo' }).click()
  await page.getByLabel('Concepto').fill('Gasto fijo pendiente')
  await page.getByLabel('Importe (ARS)').fill('226163,34')
  await page.getByRole('button', { name: 'Guardar gasto fijo' }).click()
  await page.getByRole('button', { name: 'Marcar pagada' }).first().click()
  await expect(page.getByRole('region', { name: 'Resumen del mes' })).toContainText('226.163,34')

  await page.getByRole('button', { name: 'Nuevo gasto' }).click()
  await page.getByRole('button', { name: 'Nueva categoría' }).click()
  await page.getByLabel('Nombre de categoría').fill('Comida')
  await page.getByRole('button', { name: 'Crear y usar' }).click()
  await page.getByLabel('Monto (ARS)').fill('100000')
  await page.getByLabel('Descripción (opcional)').fill('Compra del mes')
  await page.getByRole('button', { name: 'Guardar gasto' }).click()
  await expect(page.getByRole('table', { name: 'Gastos del mes' })).toContainText('100.000,00')
  await expect(page.getByRole('complementary', { name: 'Resumen por categoría' })).toContainText('100.000,00')
  await expect(page.getByText('Cambios sin guardar')).toBeVisible()

  await page.locator('summary', { hasText: 'Acciones' }).click()
  await page.getByRole('button', { name: 'Categorías' }).click()
  const categories = page.getByRole('dialog', { name: 'Categorías' })
  await categories.getByLabel('Nueva categoría').fill('Hogar')
  await categories.getByRole('button', { name: 'Crear categoría' }).click()
  await categories.getByRole('row', { name: /Comida/ }).getByRole('button', { name: 'Archivar' }).click()
  await categories.getByRole('button', { name: 'Cerrar categorías' }).click()

  await expect(page.getByRole('table', { name: 'Gastos del mes' })).toContainText('Comida')
  await page.getByRole('button', { name: 'Nuevo gasto' }).click()
  await expect(page.getByRole('option', { name: 'Comida' })).toHaveCount(0)
  await expect(page.getByRole('option', { name: 'Hogar' })).toHaveCount(1)
})
