import { expect, test } from '@playwright/test'

test('gestiona gastos, categorías archivadas y resumen del mes', async ({ page }) => {
  await page.goto('/crear')
  await page.getByLabel('Password', { exact: true }).fill('phase4-password')
  await page.getByLabel('Confirm password').fill('phase4-password')
  await page.getByRole('button', { name: 'Create vault' }).click()
  await expect(page.getByRole('heading', { name: 'Your file is ready.' })).toBeVisible()

  await page.getByRole('button', { name: 'New month' }).click()
  await page.getByLabel('Amount (ARS)').fill('3500000')
  await page.getByRole('button', { name: 'Create month' }).click()
  await expect(page.getByText('Pending fixed expenses')).toBeVisible()
  await expect(page.getByRole('region', { name: 'Monthly summary' })).toContainText('3,500,000.00')

  await page.getByRole('button', { name: 'New fixed expense' }).click()
  await page.getByLabel('Concept').fill('Paid fixed expense')
  await page.getByLabel('Amount (ARS)').fill('2000000')
  await page.getByRole('button', { name: 'Save fixed expense' }).click()
  await page.getByRole('button', { name: 'New fixed expense' }).click()
  await page.getByLabel('Concept').fill('Pending fixed expense')
  await page.getByLabel('Amount (ARS)').fill('226163.34')
  await page.getByRole('button', { name: 'Save fixed expense' }).click()
  await page.getByRole('button', { name: 'Mark as paid' }).first().click()
  await expect(page.getByRole('region', { name: 'Monthly summary' })).toContainText('226,163.34')

  await page.getByRole('button', { name: 'New expense' }).click()
  await page.getByRole('button', { name: 'New category' }).click()
  await page.getByLabel('Category name').fill('Comida')
  await page.getByRole('button', { name: 'Create and use' }).click()
  await page.getByLabel('Amount (ARS)').fill('100000')
  await page.getByLabel('Description (optional)').fill('Compra del mes')
  await page.getByRole('button', { name: 'Save expense' }).click()
  await expect(page.getByRole('table', { name: 'Monthly expenses' })).toContainText('100,000.00')
  await expect(page.getByRole('complementary', { name: 'Summary by category' })).toContainText('100,000.00')
  await expect(page.getByText('Unsaved changes')).toBeVisible()

  await page.locator('summary', { hasText: 'Actions' }).click()
  await page.getByRole('button', { name: 'Categories' }).click()
  const categories = page.getByRole('dialog', { name: 'Categories' })
  await categories.getByLabel('New category').fill('Hogar')
  await categories.getByRole('button', { name: 'Create category' }).click()
  await categories.getByRole('row', { name: /Comida/ }).getByRole('button', { name: 'Archive' }).click()
  await categories.getByRole('button', { name: 'Close categories' }).click()

  await expect(page.getByRole('table', { name: 'Monthly expenses' })).toContainText('Comida')
  await page.getByRole('button', { name: 'New expense' }).click()
  await expect(page.getByRole('option', { name: 'Comida' })).toHaveCount(0)
  await expect(page.getByRole('option', { name: 'Hogar' })).toHaveCount(1)
})
